### ISSUE TITLE
Estou com problemas para compactar um pdf com mais de uma pagina

### ISSUE THREAD

**Issue by lucianoalien** [ricardotondello/delphi_pdf_compress#1]
Esta aparecendo a seguinte mensagem quando tento compactar um arquivo pdf com mais de uma pagina:
Message: Cannot attribute gsapi_init_with_args into a instance. ErrorCode: -100 args: ?M?M?M?M?

**Comment by ricardotondello** [comment]
pode compartilhar o arquivo usado e o comando utilizado por favor?

**Comment by lucianoalien** [comment]
Estou utilizando Delphi Berlin, banco de dados Firebird e gerando o arquivo pdf com Fortes Report:
Eu verifico a variável global para identificar qual modelo de relatório vou gerar, neste caso estou usando como teste o relatório 6:
if G_MODELO_RELATORIO=6 then //
   begin
      xTotOrc:=FRM_DM.SimpleDS_ItensOrca.RecordCount;
      //aqui pego o diretório e o nome do arquivo
      frm_dm.frxPDFExport1.FileName:= G_PATH+'\'+G_pdf_NomeFile;
      frm_dm.frx_Laudo006.PrepareReport();
      frm_dm.frx_Laudo006.Export(frm_dm.frxPDFExport1);
      
      //aqui criei uma função para chamar o compactador de pdf
      CompactaPDF(G_PATH+'\'+G_pdf_NomeFile,G_PATH+'\'+'mgw'+G_pdf_NomeFile);

Abaixo esta a função:

//-----------------------
Function TFrm_Orcamento_Email.CompactaPDF(pCompFileOrig,pCompFileDest:String):Boolean;
Var oCompressPDF: TCompressPDF;
begin
    try
      oCompressPDF := TCompressPDF.Create;
      oCompressPDF.PathInput  := pCompFileOrig;
      oCompressPDF.PathOutput := pCompFileDest;
      oCompressPDF.Execute;
    except on ex:exception do
      FuncaoError('Compactação PDF',' Não foi possivel Compactar '+chr(13)+pCompFileDest,5);
    end;
    Result:=True;
end;

**Comment by lucianoalien** [comment]
Este é o arquivo pdf

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: Ricardo ***@***.***>
Enviado:quarta-feira, 13 de julho de 2022 11:26
Para: ***@***.***>
***@***.***>; ***@***.***>
Assunto: Re: [ricardotondello/delphi_pdf_compress] Estou com problemas para compactar um pdf com mais de uma pagina (Issue #1)


pode compartilhar o arquivo usado e o comando utilizado por favor?

**Comment by ricardotondello** [comment]
arquivo PDF não recebido, porem pelo oque posso ver você estas recompilando a aplicação oque eu não recomendo, pois a versa-o utilizada foi a Tokyo, oque eu recomendaria seria chamar o executável passando as variáveis conforme demonstrado no READ.ME sem a necessidade de recompilação, para quando for distribuir seu software enfie o arquivo `gsCompressPDF.exe` juntamente

**Comment by lucianoalien** [comment]
Bom dia Ricardo,
Estou passando para dizer que o motivo do erro que eu estava encontrando era que o caminho do arquivo possuía acentuação, removi a acentuação da pasta do arquivo e a compressão deu certo.

Obrigado pela atenção.

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: Ricardo ***@***.***>
Enviado:quarta-feira, 13 de julho de 2022 12:07
Para: ***@***.***>
***@***.***>; ***@***.***>
Assunto: Re: [ricardotondello/delphi_pdf_compress] Estou com problemas para compactar um pdf com mais de uma pagina (Issue #1)


arquivo PDF não recebido, porem pelo oque posso ver você estas recompilando a aplicação oque eu não recomendo, pois a versa-o utilizada foi a Tokyo, oque eu recomendaria seria chamar o executável passando as variáveis conforme demonstrado no READ.ME sem a necessidade de recompilação, para quando for distribuir seu software enfie o arquivo gsCompressPDF.exe juntamente
